LRAS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hardlanding/', include('hardlanding.urls', namespace='hardlanding')),
    url(r'^airport/', include('airport.urls', namespace='airport')),
    url(r'^pae/', include('pae.urls', namespace='pae')),
    url(r'^driving/', include('driving.urls', namespace='driving')),
    url(r'^overrun/', include('overrun.urls', namespace='overrun')),
    url(r'^index/', include('index.urls', namespace='index')),
]

airport/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.show, name='airport'),
]

driving/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^kline$', views.show_kline, name='kline'),
]

hardlanding/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^kline$', views.show_kline, name='kline'),
]

index/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

overrun/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^bar$', views.show_bar, name='bar'),
    url(r'^kline$', views.show_kline, name='kline'),
]

pae/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^ent_opt$', views.show_ent_opt, name='ent_opt'),
    url(r'^track$', views.show_track, name='track'),
    url(r'^driving_features$', views.show_driving_features, name='driving_features'),
    url(r'^progress$', views.show_progress, name='progress'),
]

driving/models.py
from django.db import models

# Create your models here.

airport/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from . import helpers
import json

def show(request):
    if request.GET:
        month = request.GET.get('month')
        airport = request.GET.get('airport')
        title, data = helpers.get_data_in_month_and_airport(month, airport)
        return JsonResponse({'title': title, 'data': data})
    else:
        result = helpers.get_maxvrtg_in_airports()
        context = {'title': '全国机场重着陆', \
                   'alldata': json.dumps(result)}
        return render(request, 'airport/airport.html', context)

driving/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from . import helpers
import json

# Create your views here.
def index(request):
    if request.GET:
        filename = request.GET.get('filename')
        alldata = helpers.get_driving_data(filename)
        if request.GET.get('json') == 'yes':
            return JsonResponse(alldata, safe=False)
        else:
            context = {'title': '驾驶模型', 'alldata': json.dumps(alldata), 
                       'files': helpers.files, 'row1': list(range(1, 7)), 'row2': list(range(7, 12))}
            return render(request, 'driving/index.html', context)
    else:
        alldata = helpers.get_driving_data()
        context = {'title': '驾驶模型', 'alldata': json.dumps(alldata), 
        'files': helpers.files, 'row1': list(range(1, 7)), 'row2': list(range(7, 12))}
        return render(request, 'driving/index.html', context)
        

hardlanding/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from . import helpers
import json

# Create your views here.
def index(request):
    if request.GET:
        col = request.GET.get('col')
        data = helpers.show_the_column(col)
        return JsonResponse(data, safe=False)
    else:
        names = helpers.get_column_names()
        context = {'mycolumns': names, 'title': '概况'}
        return render(request, 'hardlanding/index.html', context)

def show_kline(request):
    if request.GET:
        airport = request.GET.get('airport')
        airports = request.GET.get('airport_codes')
        
        if airport:    
            if airport == 'null':
                airport = None
                chinese_airport = '全国'
            else:
                chinese_airport = helpers.get_chinese_airport_name(airport)
        if airports:
            airport = airports[1: -1].split(',')
            chinese_airport = request.GET.get('title')
        vrtg = float(request.GET['vrtg'])
        counts = helpers.get_kline_counts(vrtg=vrtg, airport=airport)
        res = {'title': '{0}机场重着陆(>{1})发生频率'.format(chinese_airport, vrtg), 'counts': counts}
        for span in list('DW'):
            data_temp = helpers.get_kline(vrtg=vrtg, span=span, airport=airport)
            res['data'+span] = data_temp['vrtgp']
            res['entropy'+span] = data_temp['entropy']
            res['crossrate'+span] = data_temp['crossrate']
        # for window in [500]:
        #     res['data'+str(window)] = helpers.get_kline_ma(vrtg=vrtg, window=window, airport=airport)
        return JsonResponse(res)
    else:
        dates = helpers.get_date_range('2016-01-01', 380, 'D')
        counts = helpers.get_kline_counts(vrtg=1.4)
        geo = helpers.get_airports()
        pyramid_vrtg = helpers.get_pyramid_vrtg()
        alldata = {'dates': dates, 'counts': counts, 'airportinfo': geo['info'], 
            'altitude': geo['altitude'], 'length': geo['length'],  'pyramid_vrtg': pyramid_vrtg}
        for span in list('DW'):
            data_temp = helpers.get_kline(vrtg=1.4, span=span, airport=None)
            alldata['data'+span] = data_temp['vrtgp']
            alldata['entropy'+span] = data_temp['entropy']
            alldata['crossrate'+span] = data_temp['crossrate']
        # for window in [500]:
        #     alldata['data'+str(window)] = helpers.get_kline_ma(vrtg=1.4, window=window, airport=None)
        context = {'title': '重着陆趋势图', 'alldata': json.dumps(alldata)}
        return render(request, 'hardlanding/kline.html', context)

index/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {'title': '概况'}
    return render(request, 'index/index.html', context)

overrun/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from . import helpers
import json

# Create your views here.
def show_bar(request):
    data = helpers.get_overrun_data()
    context = {'title': '冲出跑道分布', 'data': data}
    return render(request, 'overrun/bar.html', context)

def show_kline(request):
    data = helpers.get_overrun_data()
    context = {'title': '冲出跑道趋势', 'data': data}
    return render(request, 'overrun/kline.html', context)

pae/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from . import helpers
import json

def show_ent_opt(request):
    alldata = helpers.get_all_airports_ent_opt()
    hotdata = helpers.get_heatmap_data()
    context = {'title': '所有机场的环境熵与逆转率', 'alldata': json.dumps(alldata),
               'hotdata': json.dumps(hotdata)}
    return render(request, 'pae/ent_opt.html', context)

def show_track(request):
    alldata = helpers.get_ent_opt_track()
    context = {'title': '所有机场的环境熵与逆转率质心轨迹', 'alldata': json.dumps(alldata)}
    return render(request, 'pae/track.html', context)

def show_driving_features(request):
    if request.GET:
        obj = request.GET.get('obj') # object
        ftr = request.GET.get('ftr') # feature
        cbt = request.GET.get('cbt') # combination
        span = request.GET.get('span') # frequnt
        low = request.GET.get('low')
        high = request.GET.get('high')
        res = helpers.get_driving_features(obj, ftr, cbt, span, low, high)
        return JsonResponse(res, safe=False)
    else:
        dates = helpers.get_date_range('2016-03-01', '2016-12-02', 'D')
        counts = helpers.get_kline_counts()
        alldata = {'dates': dates, 'counts': counts}
        span = 'W'
        data_temp = helpers.get_kline(span)
        alldata['entropy'+span] = data_temp['ENTROPY']
        alldata['crossrate'+span] = data_temp['crossrate']
        context = {'title': '驾驶行为特征', 'alldata': json.dumps(alldata)}
        return render(request, 'pae/driving_features.html', context)

def show_progress(request):
    res = helpers.get_progress()
    return JsonResponse(res, safe=False)

airport/templates/airport/airport.html
{% extends 'base.html' %}
    {% block content %}
        <div id="map" style="width: 100%;height:800px;"></div>
        <p id='alldata' hidden='hidden'>{{ alldata|safe }}</p>
        <p id='airporturl' hidden='hidden'>{% url 'airport:airport' %}</p>
        <p id='drivingurl' hidden='hidden'>{% url 'driving:index' %}</p>

        {% load staticfiles %}
        <script type="text/javascript" src="{% static 'js/china.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/world.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/airport.js' %}"></script>
    {% endblock %}

driving/templates/driving/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-md-3 col-md-offset">
        <div class="col-md-10">
            <div class="row">
                <h1>Capt</h1>
                <div id="stick_capt" style="width: 100%;height:250px;"></div>
            </div>
            <div class="row">
                <h1>FO</h1>
                <div id="stick_fo" style="width: 100%;height:250px;"></div>
            </div>
        </div>
        <div class="col-md-2">
            <p>
                <label for="time">时间：</label>
                <input type="text" id="time" style="border:0; color:#f6931f; font-weight:bold;">
            </p>
            <div id="slider-vertical" style="height:600px;"></div>
        </div>
    </div>
    

    <div class="col-md-9">
        <div class="row">
            <select id="select_file">
                {% for f in files %}
                    <option value="{{ f }}">{{ f }}</option>
                {% endfor %}
            </select>
            <button type="button" class="btn btn-primary" style="width: 100px" id="show">查看</button>
        </div>

        <div class="row">
            {% for i_time in row1 %}
                <div class="col-md-2">
                    <p align="center">时间片{{ i_time }}</p>
                    <div id="drv_{{ i_time }}" style="width: 100%;height:150px;"></div>
                </div>
            {% endfor %}
        </div>
        <br>
        <div class="row">
            {% for i_time in row2 %}
                <div class="col-md-2">
                    <p align="center">时间片{{ i_time }}</p>
                    <div id="drv_{{ i_time }}" style="width: 100%;height:150px;"></div>
                </div>
            {% endfor %}
        </div>

        <div class="row">
            <div id="attention" style="width: 100%;height:350px;"></div>
        </div>
    </div>

        
    <p id='alldata' hidden='hidden'>{{ alldata|safe }}</p>
    <p id='thisurl' hidden='hidden'>{% url 'driving:index' %}</p>
    {% load staticfiles %}
    <link href="{% static 'css/jquery.minicolors.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="{% static 'js/jquery.minicolors.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/driving.js' %}"></script>
{% endblock %}

hardlanding/templates/base.html
<html>
    <head>
        {% load staticfiles %}
        <meta charset="utf-8">
        <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <title>{{ title }}</title>
    </head>
    <body>
        {% include "hardlanding/nav.html" %}

        <div class="container-fluid">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>

        {% include "hardlanding/footer.html" %}
    </body>
</html>

hardlanding/templates/hardlanding/kline.html
{% extends 'base.html' %}
    {% block content %}
        <div class='col-md-4'>
            <div id="map" style="width: 100%;height:800px;"></div>
        </div>
        <div class='col-md-5'>
            <div id="kline" style="width: 100%;height:800px;"></div>
        </div>
        <div class='col-md-3'>
            <div class='row'>
                <div class='col-md-12'>
                    <div id="pyramid" style="width:100%;height:400px;"></div>
                </div>
            </div>
            <div class='row'>
                <div class='col-md-12'>
                    <div id="pie" style="width:100%;height:400px;"></div>
                </div>
            </div>
        </div>
        <p id='alldata' hidden='hidden'>{{ alldata|safe }}</p>
        <p id='klineurl' hidden='hidden'>{% url 'hardlanding:kline' %}</p>

        {% load staticfiles %}
        <script type="text/javascript" src="{% static 'js/china.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/hardlandingkline.js' %}"></script>
    {% endblock %}

hardlanding/templates/hardlanding/nav.html
<div style="background-color: #080808;height: 51px">
    <nav class="navbar navbar-inverse" role="navigation" style="background-color: #080808;height: 51px">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">着陆风险分析</a>
            </div>
            <div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'hardlanding:index' %}">...</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        重着陆分布
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'hardlanding:map' %}">机场</a></li>
                        <li><a href="{% url 'hardlanding:ent_opt' %}">环境熵与逆转率的分布</a></li>
                        <li><a href="{% url 'hardlanding:track' %}">环境熵与逆转率的质心轨迹</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'hardlanding:kline' %}">重着陆趋势</a></li>
                <li><a href="{% url 'hardlanding:overrun_bar' %}">冲出跑道分布</a></li>
                <li><a href="{% url 'hardlanding:overrun_kline' %}">冲出跑道趋势</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        ...
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">jmeter</a></li>
                        <li><a href="#">EJB</a></li>
                        <li><a href="#">Jasper Report</a></li>
                        <li class="divider"></li>
                        <li><a href="#">分离的链接</a></li>
                        <li class="divider"></li>
                        <li><a href="#">另一个分离的链接</a></li>
                    </ul>
                </li>
            </ul>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">用户</a></li>
            </ul>
            <div>
            </div>
        </div>
        </nav>

</div>

index/templates/index/index.html
{% extends 'base.html' %}
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="jumbotron" style="background: url(https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1520702176142&di=8cd21819d151aa037d3b29b4c08bf87d&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimgad%2Fpic%2Fitem%2F7e3e6709c93d70cf078de62af2dcd100baa12ba5.jpg">
                <h1 style="color: black">Welcome to LRAS!</h1>
                <p>...</p>
                <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
            </div>
        </div>

        <div class="row">
        <div class="col-md-2 col-md-offset-1">
            <div class="thumbnail">
            <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1520701378992&di=2d1aa08935e64064d344688dfffdc186&imgtype=0&src=http%3A%2F%2Fhimg2.huanqiu.com%2Fattachment2010%2F2012%2F0723%2F20120723101308689.jpg" alt="...">
            <div class="caption">
                <h3>全国机场情况</h3>
                <p>...</p>
                <p><a href="{% url 'airport:airport' %}" class="btn btn-primary" role="button">打开</a></p>
            </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="thumbnail">
            <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1520700995085&di=e8daf7a5c69521406b47b2632465f4bd&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimage%2Fc0%253Dpixel_huitu%252C0%252C0%252C294%252C40%2Fsign%3Db58dc34da6345982d187edd2658c54c1%2Fa6efce1b9d16fdfa8d0191d7bf8f8c5494ee7b9d.jpg" alt="...">
            <div class="caption">
                <h3>人机环</h3>
                <p>...</p>
                <p><a href="{% url 'pae:ent_opt' %}" class="btn btn-primary" role="button">打开</a></p>
            </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="thumbnail">
            <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1520701915269&di=ddab1bdbc0d928e56081a526f6f0dc5e&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimgad%2Fpic%2Fitem%2Fdbb44aed2e738bd4ba7a7a1caa8b87d6277ff940.jpg" alt="...">
            <div class="caption">
                <h3>着陆风险趋势</h3>
                <p>...</p>
                <p><a href="{% url 'hardlanding:kline' %}" class="btn btn-primary" role="button">打开</a></p>
            </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="thumbnail">
            <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1520701048374&di=ac88b779652a53f7a7e8e9239298884e&imgtype=0&src=http%3A%2F%2Fpic.qiantucdn.com%2F58pic%2F19%2F19%2F66%2F568449c186347_1024.jpg" alt="...">
            <div class="caption">
                <h3>驾驶环境</h3>
                <p>...</p>
                <p><a href="{% url 'driving:index' %}" class="btn btn-primary" role="button">打开</a></p>
            </div>
            </div>
        </div>
        <div class="col-md-2">
            <div class="thumbnail">
            <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1520701063458&di=485cd0b1c13ec5229b0523472b86ee34&imgtype=0&src=http%3A%2F%2Fimg02.tooopen.com%2Fimages%2F20160607%2Ftooopen_sy_164454788618.jpg" alt="...">
            <div class="caption">
                <h3>冲偏出跑道</h3>
                <p>...</p>
                <p><a href="{% url 'overrun:bar' %}" class="btn btn-primary" role="button">打开</a></p>
            </div>
            </div>
        </div>
        </div>
    </div>
    {% endblock %}

pae/templates/pae/driving_features.html
{% extends 'base.html' %}
    {% block content %}
        <div class='col-md-9 col-md-offset-0'>
            <div id="container" style="width: 100%;height:800px;"></div>
        </div>
        
        <div class='col-md-3' style="position:relative; top: 50px">
            <div class='row'>
                <div class='col-md-12' style="position:relative; top: 10px">
                    <div class="panel-group" id="accordion">
                    </div>
                </div>
            </div>
            <div class='row'>
                <div class='col-md-6'>
                    <button type="button" class="btn btn-primary" style="width: 100px" id="addpanel">添加</button>
                </div>
                <div class='col-md-6'>
                    <button type="button" class="btn btn-danger pull-right" style="width: 100px" id="deletepanel">删除</button>
                </div>              
            </div>
        </div>

        <p id='alldata' hidden='hidden'>{{ alldata|safe }}</p>
        <p id='thisurl' hidden='hidden'>{% url 'pae:driving_features' %}</p>
        <p id='progressurl' hidden='hidden'>{% url 'pae:progress' %}</p>
    
        {% load staticfiles %}
        <link href="{% static 'css/jquery.minicolors.css' %}" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="{% static 'js/jquery.minicolors.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/driving_features.js' %}"></script>
    {% endblock %}

pae/templates/pae/ent_opt.html
{% extends 'base.html' %}
    {% block content %}
        <div class='col-md-6'>
            <div id="container_scatter" style="width: 100%;height:800px;"></div>
        </div>
        <div class='col-md-6'>
            <select id="count_vrtg" onchange="select_change(this)">
                <option value="count" selected>数量分布</option>
                <option value="vrtg">平均着陆载荷</option>
            </select>
            <div id="container_hot" style="width: 100%;height:800px;"></div>
        </div>
        <p id='alldata' hidden='hidden'>{{ alldata|safe }}</p>
        <p id='hotdata' hidden='hidden'>{{ hotdata|safe }}</p>

        {% load staticfiles %}

        <script type="text/javascript" src="{% static 'js/ent_opt.js' %}"></script>
    {% endblock %}

pae/templates/pae/track.html
{% extends 'base.html' %}
    {% block content %}
        <div class='col-md-10 col-md-offset-1'>
            <div id="container" style="width: 100%;height:800px;"></div>
        </div>
        <p id='alldata' hidden='hidden'>{{ alldata|safe }}</p>

        {% load staticfiles %}
        <script type="text/javascript" src="{% static 'js/track.js' %}"></script>
    {% endblock %}

templates/base.html
<html>
    <head>
        {% load staticfiles %}
        <meta charset="utf-8">
        <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/echarts.min.js' %}"></script>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <title>{{ title }}</title>
    </head>
    <body>
        {% include "nav.html" %}

        <div class="container-fluid">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>

        {% include "footer.html" %}
    </body>
</html>

templates/footer.html
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p style="text-align:center;">
                Copyright © 2015-2018 <a href="www.buaa.edu.cn">北京航空航天大学</a>
            </p>
        </div>
    </div>
</div>

templates/nav.html
<div style="background-color: #080808;height: 51px">
    <nav class="navbar navbar-inverse" role="navigation" style="background-color: #080808;height: 51px">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:index' %}">着陆风险分析</a>
            </div>
            <div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'airport:airport' %}">全国机场情况</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        人机环
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'pae:ent_opt' %}">环境熵与逆转率的分布</a></li>
                        <li><a href="{% url 'pae:track' %}">环境熵与逆转率的质心轨迹</a></li>
                        <li><a href="{% url 'pae:driving_features' %}">驾驶行为特征</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'hardlanding:kline' %}">重着陆趋势</a></li>
                <li><a href="{% url 'driving:index' %}">驾驶模型</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        冲偏出跑道
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'overrun:bar' %}">冲出跑道分布</a></li>
                        <li><a href="{% url 'overrun:kline' %}">冲出跑道趋势</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        ...
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">jmeter</a></li>
                        <li><a href="#">EJB</a></li>
                        <li><a href="#">Jasper Report</a></li>
                        <li class="divider"></li>
                        <li><a href="#">分离的链接</a></li>
                        <li class="divider"></li>
                        <li><a href="#">另一个分离的链接</a></li>
                    </ul>
                </li>
            </ul>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">用户</a></li>
            </ul>
            <div>
            </div>
        </div>
        </nav>

</div>